import 'package:flutter/material.dart';

void main() {
  runApp(const ShopOwner());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class ShopOwner extends StatelessWidget {
  const ShopOwner({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          ShopOwnerDetail(),
        ]),
      ),
    );
  }
}

class ShopOwnerDetail extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 360,
          height: 1200,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Color(0xFFF7FAFC)),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 241,
                child: Container(
                  width: 360,
                  height: 265,
                  decoration: BoxDecoration(
                    color: Colors.white,
                    border: Border(
                      left: BorderSide(color: Color(0xFFDDE1E6)),
                      top: BorderSide(color: Color(0xFFDDE1E6)),
                      right: BorderSide(color: Color(0xFFDDE1E6)),
                      bottom: BorderSide(width: 1, color: Color(0xFFDDE1E6)),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 360,
                  height: 56,
                  decoration: BoxDecoration(color: Colors.white),
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(width: 360, height: 68),
                      ),
                      Positioned(
                        left: 16,
                        top: 16,
                        child: Container(
                          width: 24,
                          height: 24,
                          child: Stack(children: []),
                        ),
                      ),
                      Positioned(
                        left: 320,
                        top: 16,
                        child: Container(
                          width: 24,
                          height: 24,
                          child: Stack(children: []),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 23,
                top: 283,
                child: Text(
                  'Shop ratings',
                  style: TextStyle(
                    color: Color(0xFF1C1C1C),
                    fontSize: 16,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w500,
                    height: 0.09,
                  ),
                ),
              ),
              Positioned(
                left: 23,
                top: 376,
                child: Container(
                  width: 337,
                  height: 103,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 337,
                          height: 22,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Text(
                                  'Products',
                                  style: TextStyle(
                                    color: Color(0xFF8A96A4),
                                    fontSize: 16,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 0.09,
                                    letterSpacing: -0.20,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 115,
                                top: 0,
                                child: SizedBox(
                                  width: 222,
                                  child: Text(
                                    'Shirts, shops, shoes and bags',
                                    style: TextStyle(
                                      color: Color(0xFF4F4F4F),
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0.09,
                                      letterSpacing: -0.20,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 54,
                        child: Container(
                          width: 280,
                          height: 22,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Text(
                                  'Category',
                                  style: TextStyle(
                                    color: Color(0xFF8A96A4),
                                    fontSize: 16,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 0.09,
                                    letterSpacing: -0.20,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 115,
                                top: 0,
                                child: SizedBox(
                                  width: 165,
                                  child: Text(
                                    'Clothing',
                                    style: TextStyle(
                                      color: Color(0xFF4F4F4F),
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0.09,
                                      letterSpacing: -0.20,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 27,
                        child: Container(
                          width: 337,
                          height: 22,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Text(
                                  'Location',
                                  style: TextStyle(
                                    color: Color(0xFF8A96A4),
                                    fontSize: 16,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 0.09,
                                    letterSpacing: -0.20,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 115,
                                top: 0,
                                child: SizedBox(
                                  width: 222,
                                  child: Text(
                                    'Legon Hall, Main UG Campus',
                                    style: TextStyle(
                                      color: Color(0xFF4F4F4F),
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0.09,
                                      letterSpacing: -0.20,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 81,
                        child: Container(
                          width: 280,
                          height: 22,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Text(
                                  'Item num',
                                  style: TextStyle(
                                    color: Color(0xFF8A96A4),
                                    fontSize: 16,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 0.09,
                                    letterSpacing: -0.20,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 115,
                                top: 0,
                                child: SizedBox(
                                  width: 165,
                                  child: Text(
                                    'FH321',
                                    style: TextStyle(
                                      color: Color(0xFF4F4F4F),
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0.09,
                                      letterSpacing: -0.20,
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 13,
                top: 506,
                child: Container(
                  height: 93,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 334,
                          child: Text(
                            'Fashion Hub is a clothing brand with a ride range of affordable clothes for both men and women.',
                            style: TextStyle(
                              color: Color(0xFF4F4F4F),
                              fontSize: 16,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 1.02,
                        top: 74,
                        child: SizedBox(
                          width: 83.50,
                          child: Text(
                            'Read more',
                            style: TextStyle(
                              color: Color(0xFF0D6EFD),
                              fontSize: 16,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w500,
                              height: 0,
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 631,
                child: SizedBox(
                  width: 334,
                  child: Text(
                    'Phone: +233570091540',
                    style: TextStyle(
                      color: Color(0xFF4F4F4F),
                      fontSize: 16,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      height: 0.09,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 671,
                child: SizedBox(
                  width: 334,
                  child: Text(
                    'Whatsapp     : +23353231263',
                    style: TextStyle(
                      color: Color(0xFF4F4F4F),
                      fontSize: 16,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      height: 0.09,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 17,
                top: 711,
                child: SizedBox(
                  width: 334,
                  child: Text(
                    'Telegram        :  @FashionHubGH',
                    style: TextStyle(
                      color: Color(0xFF4F4F4F),
                      fontSize: 16,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w400,
                      height: 0.09,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 23,
                top: 316,
                child: Container(
                  width: 328,
                  height: 40,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 280,
                          height: 40,
                          padding: const EdgeInsets.symmetric(horizontal: 16),
                          decoration: ShapeDecoration(
                            gradient: LinearGradient(
                              begin: Alignment(0.00, -1.00),
                              end: Alignment(0, 1),
                              colors: [Color(0xFF127FFF), Color(0xFF0067FF)],
                            ),
                            shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(6)),
                          ),
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Container(
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Text(
                                      'Send inquiry',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 16,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w500,
                                        height: 0,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 280,
                          height: 40,
                          padding: const EdgeInsets.symmetric(horizontal: 16),
                          decoration: ShapeDecoration(
                            gradient: LinearGradient(
                              begin: Alignment(0.00, -1.00),
                              end: Alignment(0, 1),
                              colors: [Color(0xFF127FFF), Color(0xFF0067FF)],
                            ),
                            shape: RoundedRectangleBorder(
                                borderRadius: BorderRadius.circular(6)),
                          ),
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Container(
                                child: Row(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [
                                    Text(
                                      'Follow',
                                      textAlign: TextAlign.center,
                                      style: TextStyle(
                                        color: Colors.white,
                                        fontSize: 16,
                                        fontFamily: 'Inter',
                                        fontWeight: FontWeight.w500,
                                        height: 0,
                                      ),
                                    ),
                                  ],
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 288,
                        top: 0,
                        child: Container(
                          width: 40,
                          height: 40,
                          padding: const EdgeInsets.all(8),
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                  width: 1, color: Color(0xFFDDE1E6)),
                              borderRadius: BorderRadius.circular(6),
                            ),
                          ),
                          child: Row(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.center,
                            children: [
                              Container(
                                width: 24,
                                height: 24,
                                child: Column(
                                  mainAxisSize: MainAxisSize.min,
                                  mainAxisAlignment: MainAxisAlignment.start,
                                  crossAxisAlignment: CrossAxisAlignment.start,
                                  children: [],
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 10,
                top: 765,
                child: Container(
                  width: 340,
                  height: 107,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 12,
                        top: 76.68,
                        child: Container(
                          width: 25,
                          height: 14.27,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                          child: Stack(children: []),
                        ),
                      ),
                      Positioned(
                        left: 302,
                        top: 19.62,
                        child: Container(
                          width: 24,
                          height: 21.40,
                          child: Stack(children: []),
                        ),
                      ),
                      Positioned(
                        left: 43,
                        top: 73.12,
                        child: SizedBox(
                          width: 48,
                          height: 21.40,
                          child: Text(
                            'Ghana',
                            style: TextStyle(
                              color: Color(0xFF4F4F4F),
                              fontSize: 16,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                              letterSpacing: -0.20,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 238,
                        top: 73.12,
                        child: Container(
                          width: 88,
                          height: 21.40,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 27,
                                top: 0,
                                child: SizedBox(
                                  width: 61,
                                  height: 21.40,
                                  child: Text(
                                    'Delivery',
                                    style: TextStyle(
                                      color: Color(0xFF4F4F4F),
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0.09,
                                      letterSpacing: -0.20,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 1.78,
                                child: Container(
                                  width: 20,
                                  height: 17.83,
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    children: [],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 131,
                        top: 73.12,
                        child: Container(
                          width: 83,
                          height: 21.40,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 26,
                                top: 0,
                                child: SizedBox(
                                  width: 57,
                                  height: 21.40,
                                  child: Text(
                                    'Verified ',
                                    style: TextStyle(
                                      color: Color(0xFF4F4F4F),
                                      fontSize: 16,
                                      fontFamily: 'Inter',
                                      fontWeight: FontWeight.w400,
                                      height: 0.09,
                                      letterSpacing: -0.20,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 1.78,
                                child: Container(
                                  width: 20,
                                  height: 17.83,
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    children: [],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 10,
                        top: 62.42,
                        child: Container(
                          width: 320,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 1,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: Color(0xFFDDE1E6),
                              ),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 10,
                top: 897,
                child: Text(
                  'Other posts by FashioHub Ghana',
                  style: TextStyle(
                    color: Color(0xFF1C1C1C),
                    fontSize: 18,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w600,
                    height: 0,
                  ),
                ),
              ),
              Positioned(
                left: 23,
                top: 255,
                child: Container(
                  width: 300,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 1,
                        child: Container(
                          width: 80,
                          height: 15,
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.start,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 90,
                        top: 5,
                        child: Container(
                          width: 6,
                          height: 6,
                          decoration: ShapeDecoration(
                            color: Color(0xFFDADADA),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 208,
                        top: 5,
                        child: Container(
                          width: 6,
                          height: 6,
                          decoration: ShapeDecoration(
                            color: Color(0xFFDADADA),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 224,
                        top: 0,
                        child: Container(
                          width: 76,
                          height: 18,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 24,
                                top: 1,
                                child: Text(
                                  '154 sold',
                                  style: TextStyle(
                                    color: Color(0xFF787A7F),
                                    fontSize: 13,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 18,
                                  height: 18,
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    children: [],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 106,
                        top: 0,
                        child: Container(
                          width: 92,
                          height: 18,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 24,
                                top: 1,
                                child: Text(
                                  '32 reviews',
                                  style: TextStyle(
                                    color: Color(0xFF787A7F),
                                    fontSize: 13,
                                    fontFamily: 'Inter',
                                    fontWeight: FontWeight.w400,
                                    height: 0,
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 18,
                                  height: 18,
                                  child: Column(
                                    mainAxisSize: MainAxisSize.min,
                                    mainAxisAlignment: MainAxisAlignment.start,
                                    crossAxisAlignment:
                                        CrossAxisAlignment.start,
                                    children: [],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 56,
                child: Container(
                  width: 360,
                  height: 185,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image:
                          NetworkImage("https://via.placeholder.com/360x185"),
                      fit: BoxFit.fill,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 16,
                top: 774,
                child: Container(
                  width: 334,
                  height: 22,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: SizedBox(
                          width: 334,
                          child: Text(
                            'Instagram       : @FashionHGH',
                            style: TextStyle(
                              color: Color(0xFF4F4F4F),
                              fontSize: 16,
                              fontFamily: 'Inter',
                              fontWeight: FontWeight.w400,
                              height: 0.09,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 84,
                        top: 2,
                        child: Container(
                          width: 18.03,
                          height: 17.47,
                          child: Stack(children: []),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 91,
                top: 716,
                child: Container(
                  width: 19,
                  height: 17,
                  child: Stack(children: []),
                ),
              ),
              Positioned(
                left: 95,
                top: 676,
                child: Container(
                  width: 15.99,
                  height: 16,
                  child: Stack(children: []),
                ),
              ),
              Positioned(
                left: 53,
                top: 927,
                child: Container(
                  width: 288,
                  height: 251,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 288,
                          height: 251,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 10,
                                top: 180,
                                child: Container(
                                  width: 148,
                                  height: 57,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 23,
                                        child: SizedBox(
                                          width: 148,
                                          height: 34,
                                          child: Text(
                                            'Polo shirts collection',
                                            style: TextStyle(
                                              color: Color(0xFF8A96A4),
                                              fontSize: 13,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w400,
                                              height: 0,
                                            ),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 2,
                                        top: 0,
                                        child: SizedBox(
                                          width: 124,
                                          height: 21,
                                          child: Text(
                                            'GH₵50.30',
                                            style: TextStyle(
                                              color: Color(0xFF1C1C1C),
                                              fontSize: 16,
                                              fontFamily: 'Inter',
                                              fontWeight: FontWeight.w500,
                                              height: 0.09,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 10.47,
                                top: 6.28,
                                child: Container(
                                  width: 265.31,
                                  height: 158.97,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 8.50,
                                        top: 6.11,
                                        child: Container(
                                          width: 250,
                                          height: 149.80,
                                          padding: const EdgeInsets.only(
                                            top: 5.33,
                                            left: 15.56,
                                            right: 18.89,
                                            bottom: 11.32,
                                          ),
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(
                                              color: Colors.white),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment:
                                                MainAxisAlignment.center,
                                            crossAxisAlignment:
                                                CrossAxisAlignment.center,
                                            children: [
                                              Container(
                                                width: 215.56,
                                                height: 133.15,
                                                decoration: BoxDecoration(
                                                  image: DecorationImage(
                                                    image: NetworkImage(
                                                        "https://via.placeholder.com/216x133"),
                                                    fit: BoxFit.fill,
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 6.56,
                        top: 12.27,
                        child: Container(
                          width: 49.89,
                          height: 33.29,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 49.89,
                                  height: 33.29,
                                  decoration: ShapeDecoration(
                                    color: Color(0xFFC4C4C4),
                                    shape: OvalBorder(
                                      side: BorderSide(
                                        width: 1,
                                        strokeAlign:
                                            BorderSide.strokeAlignOutside,
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 49.89,
                                  height: 33.29,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 49.89,
                                          height: 33.29,
                                          decoration: ShapeDecoration(
                                            color: Color(0xFFC4C4C4),
                                            shape: OvalBorder(),
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 49.89,
                                          height: 33.29,
                                          decoration: BoxDecoration(
                                            image: DecorationImage(
                                              image: NetworkImage(
                                                  "https://via.placeholder.com/50x33"),
                                              fit: BoxFit.fill,
                                            ),
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
